version: '3.8'

services:
  web:
    build: .
    container_name: university_notes_bot
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads:rw
      - ./university_notes.db:/app/university_notes.db:rw
      - ./.env:/app/.env:ro
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=sqlite:///university_notes.db
      - UPLOAD_FOLDER=/app/uploads
      - TZ=Asia/Tehran
    restart: unless-stopped

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16 