services:
  - type: web
    name: university-notes-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FLASK_APP
        value: wsgi.py
      - key: FLASK_ENV
        value: production
      - key: TELEGRAM_TOKEN
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        value: sqlite:///app.db
      - key: UPLOAD_FOLDER
        value: /var/data/uploads 